defaults: &defaults
  shell: /bin/bash --login -eo pipefail
  docker:
  - image: circleci/openjdk:8-jdk-node
  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m
    TERM: dumb

build-common: &build-common
  <<: *defaults
  steps:
    - checkout
    - setup_remote_docker

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: ./gradlew clean dependencies

    - run: ./gradlew compileTestJava

    - save_cache:
        paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        key: v1-dependencies-{{ checksum "build.gradle" }}

    - run:
        name: make test
        command: |
          set -e
          export AWS_ACCESS_KEY_ID=anything_for_localstack
          export AWS_SECRET_ACCESS_KEY=anything_for_localstack
          export AWS_DEFAULT_REGION=us-west-2
          export AWS_CBOR_DISABLE=1
          make test

    - run: echo "ENVIRONMENT_NAME=${ENVIRONMENT_NAME}"

    - store_test_results:
        path: ~/build/test-results/test


version: 2
jobs:
  build-deploy-dev:
    environment:
      - ENVIRONMENT_NAME: dev
    <<: *build-common

  build-deploy-prod:
    <<: *build-common
    environment:
    - ENVIRONMENT_NAME: prod
    steps:
    - run:
        command: |
          echo "Build Prod"

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build-deploy-dev:
        filters:
          branches:
            only:
            - develop
    - approve-build-deploy-prod:
        type: approval # DO NOT REMOVE THIS
        filters:
          branches:
            only:
              - master
    - build-deploy-prod:
        requires:
            - approve-build-deploy-prod
        filters:
          branches:
            only:
              - master

